import dotenv
import os

dotenv.load_dotenv()

IS_PROD: bool = os.getenv("IS_PROD") == "TRUE"
SECRET_KEY: str = os.getenv("SECRET_KEY")
SERVER_ADRESS: str = os.getenv("SERVER_ADRESS")

SERVER_ADMIN_EMAIL: str = os.getenv("SERVER_ADMIN_EMAIL")
SERVER_ADMIN_PASSWORD: str = os.getenv("SERVER_ADMIN_PASSWORD")

TEST_JOURNALIST_EMAIL: str = os.getenv("TEST_JOURNALIST_EMAIL")
TEST_JOURNALIST_PASSWORD: str = os.getenv("TEST_JOURNALIST_PASSWORD")
TEST_EDITOR_EMAIL: str = os.getenv("TEST_EDITOR_EMAIL")
TEST_EDITOR_PASSWORD: str = os.getenv("TEST_EDITOR_PASSWORD")


ARTICLE_DB_PATH: str = os.getenv("ARTICLE_DB_PATH")
MEDIA_DB_PATH: str = os.getenv("MEDIA_DB_PATH")
USER_DB_PATH: str = os.getenv("USER_DB_PATH")
EVENT_DB_PATH: str = os.getenv("EVENT_DB_PATH")

SMTP_SENDER_ADRESS: str = os.getenv("SMTP_SENDER_ADRESS")
SMTP_SERVER_URL: str = os.getenv("SMTP_SERVER_URL")
SMTP_SERVER_PORT: str = os.getenv("SMTP_SERVER_PORT")
SMTP_SERVER_USERNAME: str = os.getenv("SMTP_SERVER_USERNAME")
SMTP_SERVER_PASSWORD: str = os.getenv("SMTP_SERVER_PASSWORD")
